{
  "pipe-parallel-size": 1,
  "model-parallel-size": 1,

  "num-layers": 24,
  "hidden-size": 1024,
  "num-attention-heads": 16,
  "seq-length": 2048,
  "max-position-embeddings": 2048,
  "pos-emb": "rotary",
  "rotary-pct": 0.25,
  "no-weight-tying": true,
  "gpt-j-residual": true,
  "output-layer-parallelism": "column",
  
  "attention-config": [[["global"], 24]],

  "scaled-upper-triang-masked-softmax-fusion": true,
  "bias-gelu-fusion": true,

  "init_method": "small_init",
  "output_layer_init_method": "wang_init",

  # "optimizer": {
  #   "type": "Adam",
  #   "params": {
  #     "lr": 0.0003,
  #     "betas": [0.9, 0.95],
  #     "eps": 1.0e-8
  #   }
  # },
  # "min_lr": 0.00003,

  "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true,
    "cpu_offload": false
  },
  # "train_batch_size": 60, #1104 # approximately 2.2M batch size across 46 nodes 
  # "train_micro_batch_size_per_gpu": 4,

  "train_micro_batch_size_per_gpu": 4,
  "gradient_accumulation_steps": 1,
  # "gas": 1,
  "data-impl": "mmap",
  # "num_workers": 1,

  "checkpoint-activations": true,
  "checkpoint-num-layers": 1,
  "partition-activations": true,
  "synchronize-each-layer": true,

  "gradient_clipping": 1.0,
  "weight-decay": 0.1,
  "hidden-dropout": 0,
  "attention-dropout": 0,

  "fp16": {
    "fp16": true,
    "enabled": true,
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 12,
    "hysteresis": 2,
    "min_loss_scale": 1
  },

  "distributed-backend": "nccl",
  "train-iters": 132,
  "lr-decay-iters": 132,
  # "warmup": 0.01,
  "checkpoint-factor": 50,
  # "extra-save-iters": [0,1,2,4,8,16,32,64,128,256,512],
  "eval-interval": 100,
  "eval-iters": 10,
  "log-interval": 10,
  "steps_per_print": 10,
  "wall_clock_breakdown": true,

  # "tokenizer-type": "HFTokenizer"
}