# Suggested data paths when using GPT-NeoX locally
{
  # "data-path": "data/enwik8/enwik8_text_document",

  # or for weighted datasets:
  "train-data-paths": [
    "/gpfs/alpine/csc499/proj-shared/incite_datasets/red_pajama_data/arxiv/arxiv_tokenized_text_document",
    "/gpfs/alpine/csc499/proj-shared/incite_datasets/red_pajama_data/book/book_tokenized_text_document",
    "/gpfs/alpine/csc499/proj-shared/incite_datasets/red_pajama_data/c4/processed_en/c4_tokenized_text_document",
    "/gpfs/alpine/csc499/proj-shared/incite_datasets/red_pajama_data/wikipedia/wiki_full_tokenized_text_document",
    "/gpfs/alpine/csc499/proj-shared/incite_datasets/red_pajama_data/github/tokenized_text_document",
    "/gpfs/alpine/csc499/proj-shared/incite_datasets/red_pajama_data/cc_classifier_filtered/2019-30/tokenized_text_document",
    "/gpfs/alpine/csc499/proj-shared/incite_datasets/red_pajama_data/cc_classifier_filtered/2020-05/tokenized_text_document",
    "/gpfs/alpine/csc499/proj-shared/incite_datasets/red_pajama_data/cc_classifier_filtered/2021-04/tokenized_text_document",
    "/gpfs/alpine/csc499/proj-shared/incite_datasets/red_pajama_data/cc_classifier_filtered/2022-05/tokenized_text_document",
    "/gpfs/alpine/csc499/proj-shared/incite_datasets/red_pajama_data/cc_classifier_filtered/2023-06/tokenized_text_document",
  ],
  "test-data-paths": ["/gpfs/alpine/csc499/proj-shared/incite_datasets/red_pajama_data/the_pile/test_tokenized_text_document"],
  "valid-data-paths": ["/gpfs/alpine/csc499/proj-shared/incite_datasets/red_pajama_data/the_pile/val_tokenized_text_document"],
  "train-data-weights": [
    2.5,
    4.5,
    15.0,
    4.5,
    4.5,
    13.4,
    13.4,
    13.4,
    13.4,
    13.4
  ],
  "test-data-weights": [
    1.
  ],
  "valid-data-weights": [
    1.
  ],

  # If weight_by_num_documents is True, Builds dataset weights from a multinomial distribution over groups of data according to the number of documents in each group.
  # WARNING: setting this to True will override any user provided weights
  # "weight_by_num_documents": false,
  # "weighted_sampler_alpha": 0.3,

  "tokenizer-type": "HFTokenizer",
  "vocab-file": "/gpfs/alpine/csc499/scratch/kshitijkg/gpt-neox/data/20B_tokenizer.json",
  # "merge-file": "data/gpt2-merges.txt",

  "save": "/gpfs/alpine/csc499/scratch/kshitijkg/continued_training/gpt-neox/checkpoints/continued_test2",
  "load": "/gpfs/alpine/csc499/scratch/kshitijkg/neox_converted/mp1_pp1/pythia",

  "checkpoint_validation_with_forward_pass": False,

  "tensorboard-dir": "tensorboard/continued_test2",
  "log-dir": "/gpfs/alpine/csc499/scratch/kshitijkg/continued_training/gpt-neox/logs/continued_test2",
  "use_wandb": False,
  # "wandb_host": "https://api.wandb.ai",
  "wandb_project": "continued_test2",

  "launcher": "jsrun",
  "deepspeed_jsrun": true,
  "finetune": true,
  "num_workers": 0,
}