{ 
  "train-data-paths": [
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_0/shard_0_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_1/shard_1_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_2/shard_2_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_3/shard_3_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_4/shard_4_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_5/shard_5_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_6/shard_6_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_7/shard_7_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_8/shard_8_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_9/shard_9_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_10/shard_10_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_11/shard_11_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_12/shard_12_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_13/shard_13_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_14/shard_14_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_15/shard_15_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_16/shard_16_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_17/shard_17_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_18/shard_18_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_19/shard_19_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_20/shard_20_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_21/shard_21_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_22/shard_22_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_23/shard_23_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_24/shard_24_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_25/shard_25_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_26/shard_26_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_27/shard_27_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_28/shard_28_text_document",
    "/gpfs/alpine/csc499/scratch/btherien/gpt-neox/data/pile/tokenized_train_debug/shard_29/shard_29_text_document",
  ],
  "train-data-weights": [
    1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.,1.
  ],
}